### ISSUE TITLE
Why you removed support for WebHost ?

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Particular/NServiceBus.Extensions.Hosting#20]
What is the recommended way to configure dependency injection with nservicebus in a netcore 3 web app?

**Comment by ramonsmits** [comment]
>NServiceBus integrates with ASP.NET Core 3.x using GenericHost. For older versions of ASP.NET Core use the community package Community.NServiceBus.WebHost. ASP.NET Core 2.x has a race condition and the community package implements a workaround. It's recommended to upgrade to ASP.NET Core 3.0 and use NServiceBus.Extensions.Hosting package.

@MichaelPetrinolis https://docs.particular.net/samples/dependency-injection/aspnetcore/

**Comment by MichaelPetrinolis** [comment]
@ramonsmits but in the sample there is a NServiceBus.Extensions.DependencyInjection project that does the same. It is just not on nuget. Do you plan to make another nuget package ?

https://github.com/Particular/docs.particular.net/blob/master/samples/dependency-injection/aspnetcore/Core_7.2/NServiceBus.Extensions.DependencyInjection/ServiceCollectionExtensions.cs

**Comment by SeanFeldman** [comment]
@MichaelPetrinolis for .NET Core 3 this is the recommended way to use NServiceBus: https://docs.particular.net/nservicebus/hosting/extensions-hosting

**Comment by MichaelPetrinolis** [comment]
Thank you, in Netcore3.0 webhost is deprecated so we must modify the bootstrap of old templates as documentation says https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0#settings-for-web-apps
