### ISSUE TITLE
System.InvalidOperationException when injecting IMessageSession

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Extensions.Hosting#24]
Based on this issue raised by a user: https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/23

## Problem description

When using `UseNServiceBus` with the host builder and other services depend on NServiceBus (by resolving the `IMessageSession` via dependency injection), there is a race condition which will make the application unusable due to the following exception when trying to resolve the message session:

>  System.InvalidOperationException: The message session can only be used after the endpoint is started. at NServiceBus.StartableEndpointWithExternallyManagedContainer

The race condition can occur when `UseNserviceBus` is called later than the dependent services (e.g. ASP.NET Core) on the host builder. Then, the following scenario can occur (assuming ASP.NET Core as the dependent service as an example):
1. ASP.NET Core registers an `IHostedService` for the web server inside `ConfigureWebHostDefaults`
1. NServiceBus registers an `IHostedService` for the NServiceBus endpoint inside `UseNserviceBus`
1. NServiceBus registers an `IMessageSession` using a factory method with the `IServiceCollection`. The session doesn't exist yet, therefore the factory method points to the lazy inside the startable endpoint: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/StartableEndpointWithExternallyManagedContainer.cs#L33
1. The host is starting up
1. Since ASP.NET Core registered first, it's hosted service is started first. The web server is now up and running
1. A web request is handled and tries tor resolve `IMessageSession` from the service provider.
1. The factory method resolves to the lazy property which throws an exception as the NServiceBus hosted service didn't complete it's startup process yet. The request fails with the exception mentioned before.
1. The NServiceBus hosted service starts. The message session exists now.
1. Even though the session exists, all further attempts to resolve the lazy value will fail due to the lazy property which has the exception cached (and the value being registered as a singleton).

Edit:

This can also occur when injecting the `IMessageSession` into a constructor of another `IHostedService`. This happens because the constructors of all hosted services are called before the hosted services are being started. Since the message session only becomes available once the NServiceBus hosted service has been started, injecting the session into any hosted service constructor causes the same exception as described above, regardless of the order of the service registration.

When trying to access the `IMessageSession` from another hosted service, injection `IServiceProvider` into the constructor and resolve the `IMessageSession` from the service provider when the `Start` method is called on the hosted service (the order of the hosted service is now relevant again, the hosted service needs to be declared after the `UseNServiceBus`.

## Potential solutions

* The easiest way to resolve this is to ensure that `UseNServiceBus` is called before dependent services.
  * Since the generic host heavily relies on ordering (see comment by @danielmarbach here: https://github.com/Particular/docs.particular.net/pull/4598#discussion_r348472642) there is no clean alternative to avoid this race condition completely.
  * Documentation has already been updated to emphasize that the order of registration is important.
  * Workaround for other hosted services trying to access an `IMessageSession`: Injection `IServiceProvider` in the ctor and resolve the message session at send-time.
* The `IMessageSession` factory should not directly resolve the lazy so that future attempts to resolve the message session at least get the message session. This way, the impact of the race condition is minimized to the duration of the endpoint hosted service startup time. This is similar to the behavior of the ASP.NET Core 2 sample behavior we had on the documentation for a while.
  * Doing so might also hide this behavior and incorrectly ordered configuration though.
* A custom `IMessageSession` implementation can internally delay session access until the endpoint is fully started. This approach is used in this community package to support ASP.NET Core 2 due to the behavior of the web host which causes a very similar race condition: https://github.com/timbussmann/Community.NServiceBus.WebHost
  * This approach was avoided for the ASP.NET Core 3 implementation due to the possibilities of the guaranteed order of startup. The custom message session can have unknown side effects in combination with other downstream packages, requires synchronization logic and increases complexity.
* Introduce a new API, e.g. `IMessageSessionProvider` which is immediately registered and available for constructor injection. It has a single property e.g. `CurrentSession` which then resolves the actual message session when accessing the message property. This allows injecting the "session" into the constructor while the actual resolving will happen at send-time. Note that this also won't allow sending messages from a hosted service constructor but that's to expected behavior. The provider can either verify that the endpoint has been properly started already (ensuring order) or asynchronusly block the send-operation till the endpoint started (see https://github.com/timbussmann/Community.NServiceBus.WebHost/blob/master/src/Community.NServiceBus.WebHost/WebHostCompatibleMessageSession.cs )

**Comment by danielmarbach** [comment]
Quick question: Bullet point two is talking about changing https://github.com/Particular/NServiceBus.Extensions.Hosting/blob/master/src/NServiceBus.Extensions.Hosting/HostBuilderExtensions.cs#L23 to "transient"?

**Comment by timbussmann** [comment]
@danielmarbach potentially yes, if we would remove the lazy, we would probably also have to remove the singleton scope. I haven't checked whether the exception is also cached by the DI container or just the lazy.

**Comment by danielmarbach** [comment]
I think this is a bug in the core because we use the default constructor of Lazy. We should be using `LazyThreadSafetyMode.PublicationOnly`

```
If the mode is LazyThreadSafetyMode.ExecutionAndPublication or LazyThreadSafetyMode.None, there is no second chance to initialize the Lazy<T> instance. If an exception occurs and is unhandled in the initialization function, that exception is cached and rethrown on subsequent accesses of the Lazy<T>.Value property. No value is created if an exception is thrown, so in such cases IsValueCreated returns false.
```

but with PublicationOnly

```
If the mode is LazyThreadSafetyMode.PublicationOnly, the first thread that succeeds in running the initialization function (or the parameterless constructor) creates the value for the Lazy<T> instance. If the initialization function throws an exception on one thread, other threads can still try to initialize the Lazy<T> instance. Until the value is created, the IsValueCreated property returns false.
```

it would work

**Comment by corstian** [comment]
One issue I'm currently dealing with is that I wish to use the `IMessageSession` within another `IHostedService` which is registered as being a singleton instance.

Looking for a solution, I think one of the most straightforward solutions would be to implement a `TaskCompletionSource<IMessageSession>` which gets set from the `NServiceBusHostedService`, but this will result in quite a confusing class coupling, given that there is a dependency on the service provider. Any ideas?

**Comment by corstian** [comment]
So the solution I ended up settling with was to create a custom `IMessageSession` implementation which acts as a proxy. Upon startup a new instance of this `MessageSessionProxy` is registered as an `IMessageSession` with the DI container. After the service bus is set up, the `NServiceBusHostedService` will pull this instance from the dependency service, and set it's value.

Hence:
- Coupling is minimal
- Exceptions can be thrown on method level when no `IMessageSession` is available, and will work as expected when the connection is available.
- The interface is honoured
- The DI implementation can be requested and used from another singleton instance without missing the one change you have at getting the `IMessageSession`

**Comment by timbussmann** [comment]
> One issue I'm currently dealing with is that I wish to use the IMessageSession within another IHostedService which is registered as being a singleton instance.

@corstian this is a known problem due to the way the generic host is working. Different `IHostedService` can't use ctor DI injection in case the dependency is setup as part of the services startup. This is due to the behavior of the generic host which resolves all `IHostedServices` at once and then sets them up after each other. Therefore ctor injections on the service itself happens before everything is available.

> Looking for a solution, I think one of the most straightforward solutions would be to implement a TaskCompletionSource<IMessageSession> which gets set from the NServiceBusHostedService, but this will result in quite a confusing class coupling, given that there is a dependency on the service provider. Any ideas?

This works but is very risky as an incorrect order of the services (e.g. due to incorrect configuration) will cause a full deadlock on the host.

Currently, we recommend resolving the `IMessageSession` via the service provider manually within the hosted services start method. Here's a similar discussion about this on our docs repository: https://github.com/Particular/docs.particular.net/issues/4601

The proxy approach also works but we're currently not sure whether it makes sense to provide this by default as the proxy can potentially cause conflicts with other NServiceBus packages or cause unexpected behavior when users aren't aware of the proxy.

**Comment by timbussmann** [comment]
updated the issue to include the case where `IMessageSession` is injection into a constructor of another hosted service. /cc @danielmarbach

**Comment by evolvedlight** [comment]
@timbussmann we have the same issue here - we have an old messaging interface where we take the old messages and republish as nservicebus messages. We've done this with an IHostedService but the IHostedService needs an IMessageSession to be able to send the messages.

We'd also prefer it if there was the extension method on IServiceCollection instead of on IHostBuilder, allowing us to not have extra unwanted stuff in Program.cs but instead in Startup.cs where it'd normally belong.

We workaround for now with a custom proxy, as the above, but we'd prefer not to.

Cheers,
Steve

**Comment by timbussmann** [comment]
> We'd also prefer it if there was the extension method on IServiceCollection instead of on IHostBuilder

Can you show me some "sample (pseudo) code" which would show how you'd like the API to look like and how you would use it (in regards to the ServiceCollection extension method)?

as a "workaround", I'd recommend to inject `IServiceProvider` into a hosted service and then resolve the message session at send-time or to use a FeatureStartupTask, those two options should work fairly well (but require a bit of boilerplate code).

**Comment by johnkors** [comment]
I tried the injecting the ServiceProvider approach. It works, but throws exceptions on shutdown _when using the Microsoft Logger extension_.

```
Unhandled exception. System.AggregateException: One or more hosted services failed to stop. (The type initializer for 'NServiceBus.RunningEndpointInstance' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'NServiceBus.RunningEndpointInstance' threw an exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Extensions.Logging.LoggerFactoryExtensions.CreateLogger(ILoggerFactory factory, Type type)
   at LoggerFactory.GetLogger(Type type) in C:\projects\nservicebus-microsoftlogging\src\NServiceBus.MicrosoftLogging\LoggerFactory.cs:line 19
```

**Comment by danielmarbach** [comment]
@johnkors I see you are using the community extension for MS logging. Do you resolve a new logger while shutting down? Can you share the code with us somewhere so that we can have a look at it and point out what is missing? That would greatly speed up our ability to help you or discover potential problems our code might have

**Comment by johnkors** [comment]
Ah, I see what's wrong in my code now. The community logger package [also requires correct ordering](https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging#in-a-generic-host). Moving it to before `UseNServiceBus` resolved it. Nevermind [my comment](https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/24#issuecomment-594168759) :)

```diff
+      .UseMicrosoftLogFactoryLogging()
       .UseNServiceBus()
-      .UseMicrosoftLogFactoryLogging()

**Comment by evolvedlight** [comment]
> Can you show me some "sample (pseudo) code" which would show how you'd like the API to look like and how you would use it (in regards to the ServiceCollection extension method)?

Sure, what we have is quite a few microservices which all have similar boilerplate code but with some customisations depending on the configuration or environment. That runs to about 75 lines of code and does things like:

           ```
 if (env.EnvironmentName == "local")
            {
                <setup for the local authentication>
            }
            else
            {
                <setup for the server authentication (uses values in _configuration), other production specific things like location of certs>
                endpointConfiguration.License(configuration.GetValue<string>("nsb_license"));

                var metrics = endpointConfiguration.EnableMetrics();
                metrics.SendMetricDataToServiceControl(
                    serviceControlMetricsAddress: "Particular.Monitoring.RabbitMq",
                    interval: TimeSpan.FromSeconds(2));
            }
```

We wrap this (company specific, team specific) logic up into an extension method and then call it like:

```
services.AddStandardRabbitEndpoint(_configuration, _env, "<name of our service>, c =>
{
    c.UseSqlPersistence = false;
});
```
_configuration is IConfiguration
_env is IWebHostEnvironment

We also use SQL persistence for some services  so have logic wrapped up depending on the config for which table to use, etc. Some of this comes from the appsettings.json files, so we'd like to have access to those when we configure NServiceBus.

At Program.cs time we don't have access to the config values, so the NServiceBus integration would be much more difficult.

**Comment by timbussmann** [comment]
It sounds like you're trying to configure NServiceBus as part of the ASP.NET Core configuration (inside `ConfigureWebHostDefaults`)? NServiceBus is configured directly on the host builder, not via `services.AddXyz`. NServiceBus is hosted as a dedicated "background task" (hosted service) in addition to the web server.

> At Program.cs time we don't have access to the config values, so the NServiceBus integration would be much more difficult.

What config values do you not have access to? The `UseNServiceBus` method receives a context which gives access to `IHostEnvironment` and `IConfiguration`.

**Comment by evolvedlight** [comment]
@timbussmann thanks; I'll give that a go. I just thought that these kinda things are "supposed" to go in ConfigureServices but I'm willing to accept that's not the case

**Comment by evolvedlight** [comment]
@timbussmann all good using the IServiceProvider workaround - but I'd like to replace that with something as suggested above that would give a lazy IMessageSession or something similar that we can inject directly.

**Comment by timbussmann** [comment]
@evolvedlight thanks for the feedback, I've raised an internal issue about this. I hope we can make it a bit easier for users to get access to a message session in other hosted services :)

**Comment by joacar** [comment]
I'm using RabbitMQ as transport mechanism and if RabbitMQ cluster is down or it takes time to establish a connection, the application is stuck at the hosted service and can't handle traffic. For my use case the app can function without NServiceBus, but the current implementation doesn't work like that. Do anyone have any ideas how to workaround that?

**Alternative implementation**
The hosted service could start a new task in `StartAsync` dedicated to starting the endpoint and return immediately. This would

1. None blocking
1. Possibility to implement retry functionality with respect to establish connection

However it would break the ordering and subsequent code dependent on `IMessageSession` need to be changed to `Func<IMessageSession>` and all changes that it brings.

**Comment by timbussmann** [comment]
hm that's an interesting point @joacar . As you already said, changing the startup behavior to work completely asynchronous from the host's startup process could mean complicated race conditions when using the message session in other hosted services or complicate the usage by forcing the user to always handle the potential situation of an unstarted endpoint with every access to the session.

**Comment by joacar** [comment]
@timbussmann I created a PR (see link in thread) to address the resilience part. 
The handling of message session if connection hasn’t been established upon usage isn’t covered.

**Comment by danielmarbach** [comment]
We have improved the session management in 1.1.0 and properly guide now with a transient/recoverable exception when the session is used too early. Details available in this [section of the documentation](https://docs.particular.net/nservicebus/hosting/extensions-hosting#configuration).
