### ISSUE TITLE
[.NET 8] Add Extension to UseNServiceBus with the new generic IHostApplicationBuilder

### ISSUE THREAD

**Issue by kylejuliandev** [Particular/NServiceBus.Extensions.Hosting#429]
### Describe the feature.

.NET 8 appears to be shipping with an extension to the new generic "minimal api" approach. This will enable a more consistent interface for hosting both APIs and Worker services (see https://github.com/dotnet/runtime/issues/85486). It would be great to introduce an extension on IHostApplicationBuilder to permit initialising and starting up a NServiceBus host, as an alternative approach to the previous [Generic Host](https://learn.microsoft.com/en-us/dotnet/core/extensions/generic-host) method. Typical ceavets would apply, such as not being able to initialise or run the `IHostApplicationBuilder.UseNServiceBus` approach more than once.

Example usage would look like

### API

<img src="https://github.com/Particular/NServiceBus.Extensions.Hosting/assets/38759683/9ddac658-2963-4c34-a4e6-d88b78e98045" width="500" />

### Worker

<img src="https://github.com/Particular/NServiceBus.Extensions.Hosting/assets/38759683/10f41dc8-5f5f-41fd-a067-35907fc7397a" width="500" />

**Comment by RenaudGelai** [comment]
Hello @bording, any idea on when this will be available in the nuget package ? Thanks in advance. Best regards.

**Comment by bording** [comment]
@RenaudGelai This will be part of the new 3.0.0 package that we'll be releasing as part of NServiceBus 9. We don't have a specific ETA on that yet though.
