### ISSUE TITLE
No built-in support integration with Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Extensions.Hosting#46]
The generic host uses [Microsoft.Extensions.Logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging) as the built-in logging abstraction. The logger is managed by the generic host and configurable via `hostBuilder.ConfigureLogging(...)`.

NServiceBus doesn't use the configured logger for it's logging output, as it continues to rely on the `LogManager` defined in NServiceBus. The LogManager needs to be configured before using any other NServiceBus API since the static caching of loggers (via `static ILog logger = LogManager.GetLogger<T>()`) will cache the logger the first time it is resolved. Many NServiceBus internal classes resolve the logger as part of the endpoint configuration & startup procedure which begins as part of calling `UseNServiceBus` (as it calls `EndpointWithExternallyManagedContainer.Create` internally). This means the logger is resolved before the logger managed by the generic host is available (as it is only available once the `IServiceProvider` has been built). Therefore, these two loggers are hard to integrate out-of-the-box.

A workaround also shown by our [generic host sample](https://docs.particular.net/samples/hosting/generic-host/) is to use a community package written by Simon Cropp which is available here: https://www.nuget.org/packages/NServiceBus.MicrosoftLogging.Hosting/ (see the [GitHub readme for usage](https://github.com/NServiceBusExtensions/NServiceBus.MicrosoftLogging#in-a-generic-host)).

**Comment by HEskandari** [comment]
I have made a note on two of our samples that currently you need to use a community package for this. You can find the PR for the future reference [here](https://github.com/Particular/docs.particular.net/pull/4935).
