### ISSUE TITLE
Add service collection to AddNServiceBus IHostBuilder Extension

### ISSUE THREAD

**Issue by bleepzter** [Particular/NServiceBus.Extensions.Hosting#75]
For the purpose of using .NET Core's DI container in configuring the endpoint configuration we should be able to retrieve instances of classes that configure the actual endpoint configuration from settings. This is currently not possible because of the following:
- The configuration is not accessible from within your extension method. You have to new up a `ConfigurationBuilder` and manually get an instance of `IOptions<T>` where T represents your configuration values.
- If you have classes that configure your `EndpointConfiguration` you can't get an instance of that class. 

The extension method changes proposed are as follows:
```csharp
/// <summary>
/// Configures the host to start an NServiceBus endpoint.
/// </summary>
public static IHostBuilder UseNServiceBus(this IHostBuilder hostBuilder, Func<HostBuilderContext, IServiceCollection, EndpointConfiguration> endpointConfigurationBuilder)
{
    hostBuilder.ConfigureServices((context, serviceCollection) =>
    {
        var endpointConfiguration = endpointConfigurationBuilder(context, serviceCollection);
        var startableEndpoint = EndpointWithExternallyManagedContainer.Create(endpointConfiguration, new ServiceCollectionAdapter(serviceCollection));

        serviceCollection.AddSingleton(_ => startableEndpoint.MessageSession.Value);
        serviceCollection.AddSingleton<IHostedService>(serviceProvider => new NServiceBusHostedService(startableEndpoint, serviceProvider));
    });

    return hostBuilder;
}
```

The usage scenario will allow to resolve services and types used to configure the `EndpointConfiguration`.

```csharp
public static class Program
{
    public static void Main(string[] args)
    {
        Program.CreateHostBuilder(args).Build().Run();
    }

   private static IHostBuilder CreateHostBuilder(string[] args)
   {
        return Host.CreateDefaultBuilder(args)
           .UseServiceProviderFactory(new AutofacServiceProviderFactory())
           .ConfigureServices(services =>
           {
               services.AddOptions<JsonSettingsOptions>();
               services.AddTransient<IJsonSettingsProvider , JsonSettingsProvider>();
           })
          .UseNServiceBus( (hostBuilderContext, serviceCollection) =>
          {
             var endpointConfig = new EndpointConfiguration("MyEndPoint");
             
             using (var scope = services.BuildServiceProvider().CreateScope())
             {
                   var provider = scope.ServiceProvider.GetService<IJsonSettingsProvider>();
                   provider.Configure(endpointConfig);
             }

             return endpointConfig;
        });
    }
}

// This class represents an object that is rehidreted from the appsettings.{environment}.json or appsettings.json
public class JsonSettingsOptions
{ 
    public bool Indent { get; set; }
}

//defines a contract for objects that are used to configure aspects of the EndpointConfiguration.
public interface IJsonSettingsProvider 
{
    void Configure(EndpointConfiguration endpointConfig);
}

//cofnigures a JsonSerializer for the EndpointConfiguration
public class JsonSettingsProvider : IJsonSettingsProvider 
{
    private readonly JsonSettingsOptions options;

    public JsonSettingsProvider(IOptions<JsonSettingsOptions> options)
    {
         this.options = options?.Value ?? throw new ArgumentNullException(nameof(options));
    }

   public void Configure(EndpointConfiguration endpointConfig)
   {
        var jsonSerializationSettings = new JsonSerializerSettings();
      
        if(this.options.Indent){
            jsonSerializaitonSettings.Formatting = Formatting.Indented;
        }
       
        var serialization = endpointConfig.UseSerialization<NewtonsoftSerializer>();
        serialization.Settings(jsonSerializationSettings);
    }
}

```

**Comment by HEskandari** [comment]
Thanks for the suggestion @bleepzter. We'll consider it when we do an enhancement release on `NServiceBus.Extensions.Hosting` package next.

**Comment by bleepzter** [comment]
This is perhaps the most important thing you can do to this hosting code. No offense - but even with the "adapters" for the service collection and the NServiceBus hosted service - your technology stack is still not friendly for .NET Core. 

I understand that NServiceBus is quite opinionated and it implements its own DI per endpoint. This allows to have multiple endpoints in the same application, with various services resolved per each message handler. I am ok with that. That's why we have the understanding if you have a .NET Core app - you should have at most one endpoint and at most one NServiceBus hosted service due to the limitations of how the .NET Core DI container works (service collection). So far - we are ok. We can live with this.

The problem I am having and I urge you to address - is with the configuration of the endpoint. l does not work with .NET Core. 
Since we don't have access to the service collection or the DI container - we have no way of retrieving instance of objects that configure the endpoint out of that container. 

The extension method that you created - within that method we are forced to figure out ways to not only to construct objects that configure the endpoint (perhaps by reading from some type of config source) - but also how to get a hold of that config in the first place. Without exposing that service collection - you are forcing people to:

- Instantiate concrete objects; or create a new DI container; or use some sort of reflection - to create objects used to configure the endpoint. Why?!? (facepalm)

- Write spaghetti to procedurally configure the endpoint. In other words - within the confines of the extension methods we hardcode all values of the endpoint configuration. (facepalm x2). This is something you probably highly encourage considering the API surface of NServiceBus, but it really doesn't sit well with most people who want to drive the values at start up through config. 

- Write even more spaghetti to get access to IConfigurationRoot. Why!?! (facepalm x3).  We'd most likely have to crate a new instance of the config builder and build it, so we can get an IConfigurationRoot and the values we need at runtime. Typically we can get the configuration from the DI container - however, since the DI container is not exposed we have to use workarounds. 

As you know - IConfigurationRoot combines all configuration sources across the entire .NET ecosystem ranging from json files, to xml, to remote key value stores (eg: Azure Key Vault, Redis, etc..). therefore - we need it to access the values used to configure the endpoint. 

Now let's expand on this shall we? - Lets use IOptions<T> and the create a strong type (T) that combines the several logical config values and register that type with the .NET Core service collection. This is done through the ServiceCollection.Use<T>() extension method which binds the type to the config values. 

Since the container is not exposed - we can't get the instance of IOptions<T> to configure your endpoint therefore we still have to do the gymnastics described above.

In reality - not addressing this soon is really annoying and alienating .NET Core devs. I don't want to copy your code, fix it, and rebuild it, because that makes me have ownership of something I am not an owner of. If I use the modified code with any of my clients - I am responsible for maintaining that codebase until you fix your .... code. That's the least you can do.

And if you claim you support .NET Core 3+ - at least fix the code to use the same extension method pattern for configuring the endpoint. Use the appropriate .NET Core 3 mechanisms and stop going against the programming model.

**Comment by andreasohlund** [comment]
Hi @bleepzter , I was trying to digg deeper into your use case and something doesn't feel right. In general, you should not rely on DI in the configuration phase but rather in things like [`IHostedService`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostedservice?view=dotnet-plat-ext-3.1). Resolving from DI to early can break some containers like [Autofac that is immutable after first resolve.](https://autofaccn.readthedocs.io/en/latest/best-practices/#consider-a-container-as-immutable)

This is also why you have to use the [ServiceProvider.GetService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider.getservice?view=dotnet-plat-ext-3.1) workaround to be able to resolve the options.

The Microsoft APIs tends to either provide constructor injection or pass `IServiceProvider` into methods where DI is "supposed" to be used in my experience.

Looking at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-3.1 I would say that the options extension can be used without DI to configure NServiceBus itself but you could use DI to configure things that you use your self eg. 

```
serviceCollection.AddTransient<MyClass>(serviceProvider => 
   new MyMyClass(serviceProvider.GetService<IJsonSettingsProvider>().SomeSetting))
```

Does this make any sense?

**Comment by marcselis** [comment]
@andreasohlund: I'm experiencing the same problem. I want to access a registered service that can build and configure the EndpointConfiguration in the UseNServiceBus method.  See Non Critical Case #00058008 for more information and a sample application.

**Comment by andreasohlund** [comment]
@marcselis what is it that you need to resolve from DI during configuration?

Our stance that DI should not be used in the configuration phase still stands as mentioned above so I'm not sure that is much we can do here since it goes against the design of the generic host as far as we can tell.

**Comment by andreasohlund** [comment]
As you can see here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#recommendations MS recommends to not use `services.GetServices`. Unfortunately `Microsoft.Extensions.Configuration` is incompatible with this approach.

**Comment by andreasohlund** [comment]
@bleepzter it seems like accessing IConfiguration via the `[HostBuilderContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostbuildercontext)` is the way (or at least one way) that Microsoft allows IConfiguration to be used at configuration time without relying on DI. 

https://docs.particular.net/nservicebus/bridge/configuration#hosting shows this in action, would that work for your scenario?

**Comment by andreasohlund** [comment]
We also have a sample showing how to use this approach. 

https://docs.particular.net/samples/platform-connector/ms-config/

Closing this, please let us know if the mentioned approach doesn't work for you
